# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  ElementaryNN_config = debug
endif
ifeq ($(config),release)
  ElementaryNN_config = release
endif
ifeq ($(config),dist)
  ElementaryNN_config = dist
endif

PROJECTS := ElementaryNN

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

ElementaryNN:
ifneq (,$(ElementaryNN_config))
	@echo "==== Building ElementaryNN ($(ElementaryNN_config)) ===="
	@${MAKE} --no-print-directory -C ElementaryNN -f Makefile config=$(ElementaryNN_config)
endif

clean:
	@${MAKE} --no-print-directory -C ElementaryNN -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   ElementaryNN"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"